version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=krazy
      - MYSQL_PASSWORD=ideas
      - MYSQL_USER=krazy
      - MYSQL_ROOT_PASSWORD=krazyideas
  backend:
    image: krazyideas/backend:v0.0.6
    ports:
      - "8080:8080"
    links:
      - mysql
    volumes:
        - ~/backendConfig:/usr/src/myapp/config:ro
  frontend:
    image: krazyideas/frontend:v0.0.4
    ports:
      - "3000:3000"
    links:
      - backend
    volumes:
        - ~/frontendConfig:/usr/src/myapp/conf:ro
